my_image = imread('images\lena512color.tiff');
grey_image = rgb2gray(my_image);
%[x y] = size(grey_image);
%ones_array = ones(x, y);
%max_array = ones_array * 255;
%negative = max_array - grey_image;
%negative = imsubtract(grey_image, 255);
negative = 255 - grey_image;
%img_double = im2double(grey_image);
img_double = im2double(negative);
log_image = 2 * log (1 + img_double);
%log_image = reallog(grey_image);
figure;
subplot(221);
imshow(my_image);
subplot(222);
imshow(grey_image);
subplot(223);
imshow(negative);
subplot(224);
imshow(log_image);
%imagesc(negative);
